### ISSUE TITLE
메인 피드 - data class 설계

### ISSUE THREAD

**Issue by tbtzpdlql** [boostcampth/boostcamp3_G#145]
﻿### 개요
- 화면에 보여질 데이터 클래스를 작성한다.

<hr>

### 체크리스트
- [ ] 데이터바인딩을 고려할 것
- [ ] repository 인터페이스 설계를 고려할 것
- [ ] 데이터 내용이 꼭 필요한지 검사할 것

**Comment by zeropol2** [comment]
데이터바인딩을 고려할 필요는 없을 것 같네요
